# Generated by Django 5.2.8 on 2025-11-30 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dir', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fc', models.CharField(max_length=150)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.direction')),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.direction')),
                ('id_fonc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.fonction')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Adresse e-mail')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('telephone', models.IntegerField(null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='utilisateur_groups', related_query_name='utilisateur', to='auth.group')),
                ('localite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateur.localite')),
                ('poste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateur.poste')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='utilisateur_permissions', related_query_name='utilisateur', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
