# Generated by Django 5.2.8 on 2025-11-30 21:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plainte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_chrono_tkk', models.CharField(editable=False, max_length=50, unique=True, verbose_name='N° Chrono TKK')),
                ('date_plainte', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Dates')),
                ('ny_mpitory', models.TextField(verbose_name='Ny Mpitory (Le Plaignant)')),
                ('tranga_kolikoly', models.TextField(verbose_name='Tranga Kolikoly (Le Fait/Acte de Corruption)')),
                ('ilay_olona_kolikoly', models.TextField(verbose_name="Ilay Olona Manao kolikoly (L'auteur de la corruption)")),
                ('toorna_birao', models.TextField(blank=True, null=True, verbose_name='Toerana - Birao - Sampan-draharaha manao ilay kolikoly (Lieu - Bureau - Service de la corruption)')),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente'), ('COURS', 'En cours de traitement'), ('TRAITEE', 'Traitée')], default='ATTENTE', max_length=10, verbose_name='Statut de la plainte')),
            ],
            options={
                'verbose_name': 'Plainte en ligne',
                'verbose_name_plural': 'Plaintes en ligne',
                'ordering': ['-date_plainte'],
            },
        ),
    ]
