# Generated by Django 5.2.8 on 2025-11-30 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_plainte'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistreArrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_enr_arrive', models.CharField(editable=False, max_length=20, unique=True, verbose_name='N° ENR Arrivé')),
                ('date_arrivee', models.DateField(default=django.utils.timezone.now, verbose_name='Date d’arrivée')),
                ('date_correspondance', models.DateField(verbose_name='Date Correspondance')),
                ('nature', models.CharField(choices=[('lettre', 'Lettre'), ('email', 'Email'), ('fax', 'Fax')], max_length=50, verbose_name='Nature')),
                ('provenance', models.TextField(verbose_name='Provenance')),
                ('texte_correspondance', models.TextField(verbose_name='Texte de la correspondance')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observation')),
            ],
            options={
                'verbose_name': 'Registre Arrivé',
                'verbose_name_plural': 'Registres Arrivés',
                'ordering': ['-date_arrivee', '-id'],
            },
        ),
    ]
