# Generated by Django 5.2.8 on 2025-12-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_registrearrive'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrearrive',
            name='statut_traitement',
            field=models.CharField(choices=[('ATTENTE', 'En attente'), ('COURS', 'En cours de traitement'), ('TRAITEE', 'Traitée'), ('CSS', 'Classer sans suite')], default='COURS', max_length=10, verbose_name='Statut du Traitement'),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='statut',
            field=models.CharField(choices=[('ATTENTE', 'En attente'), ('COURS', 'En cours de traitement'), ('TRAITEE', 'Traitée'), ('CSS', 'Classer sans suite')], default='ATTENTE', max_length=10, verbose_name='Statut de la plainte'),
        ),
        migrations.AlterField(
            model_name='registrearrive',
            name='nature',
            field=models.CharField(choices=[('lettre', 'Lettre'), ('email', 'Email'), ('fax', 'Fax'), ('main', 'Dépôt à la main')], max_length=50, verbose_name='Nature'),
        ),
    ]
