# Generated by Django 5.2.8 on 2025-12-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_registrearrive_statut_traitement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plainte',
            name='n_chrono_tkk',
            field=models.CharField(editable=False, max_length=50, verbose_name='N° Chrono TKK'),
        ),
    ]
