# Generated by Django 5.2.8 on 2025-12-04 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_alter_plainte_n_chrono_tkk'),
    ]

    operations = [
        migrations.AddField(
            model_name='plainte',
            name='utilisateur_creation',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaintes_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='plainte',
            name='utilisateur_modification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaintes_modifiees', to=settings.AUTH_USER_MODEL, verbose_name='Dernière modification par'),
        ),
        migrations.AddField(
            model_name='registrearrive',
            name='utilisateur_creation',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registres_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='registrearrive',
            name='utilisateur_modification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registres_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Dernière modification par'),
        ),
    ]
