# Generated by Django 5.2.8 on 2025-12-10 19:18

import utilisateur.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0006_plainte_utilisateur_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plainte',
            name='piece_jointe',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=utilisateur.models.plainte_directory_path, verbose_name='Pièce jointe (PDF, Image...)'),
        ),
    ]
