# Generated by Django 5.2.8 on 2025-12-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0007_plainte_piece_jointe'),
    ]

    operations = [
        migrations.AddField(
            model_name='plainte',
            name='pac_affecte',
            field=models.CharField(blank=True, choices=[('PAC-TANA', 'PAC ANTANANARIVO'), ('PAC-FIANARA', 'PAC FIANARANTSOA'), ('PAC-MAHA', 'PAC MAHAJANGA')], max_length=50, null=True, verbose_name='PAC Affecté'),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='statut',
            field=models.CharField(choices=[('ATTENTE', 'En attente'), ('COURS', 'En cours de traitement'), ('TRAITEE', 'Traitée'), ('DISPATCHE', 'Dispatche'), ('CSS', 'Classer sans suite')], default='ATTENTE', max_length=10, verbose_name='Statut de la plainte'),
        ),
        migrations.AlterField(
            model_name='registrearrive',
            name='statut_traitement',
            field=models.CharField(choices=[('ATTENTE', 'En attente'), ('COURS', 'En cours de traitement'), ('TRAITEE', 'Traitée'), ('DISPATCHE', 'Dispatche'), ('CSS', 'Classer sans suite')], default='COURS', max_length=10, verbose_name='Statut du Traitement'),
        ),
    ]
