# Generated by Django 5.2.8 on 2025-12-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0008_plainte_pac_affecte_alter_plainte_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plainte',
            name='pac_affecte',
            field=models.CharField(blank=True, choices=[('ANTANANARIVO', 'ANTANANARIVO'), ('FIANARANTSOA', 'FIANARANTSOA'), ('MAHAJANGA', 'MAHAJANGA')], max_length=50, null=True, verbose_name='PAC Affecté'),
        ),
    ]
