# Generated by Django 5.2.8 on 2025-12-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0009_alter_plainte_pac_affecte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrearrive',
            name='nature',
            field=models.CharField(choices=[('lettre', 'Lettre'), ('email', 'Email'), ('fax', 'Fax'), ('main', 'Dépôt à la main'), ('plainte', 'Plainte en ligne'), ('opj', 'OPJ')], max_length=50, verbose_name='Nature'),
        ),
    ]
