# Generated by Django 5.2.8 on 2025-12-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0010_alter_registrearrive_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='plainte',
            name='est_anonyme',
            field=models.BooleanField(default=False, verbose_name='Plainte Anonyme'),
        ),
    ]
