# Generated by Django 5.2.8 on 2025-12-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0011_plainte_est_anonyme'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrearrive',
            name='n_plainte_associe',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Plainte Associée'),
        ),
    ]
