# Generated by Django 5.2.8 on 2025-12-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0012_registrearrive_n_plainte_associe'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrearrive',
            name='est_valide',
            field=models.BooleanField(default=False, verbose_name='Validé (avec N° RA)'),
        ),
        migrations.AlterField(
            model_name='registrearrive',
            name='n_enr_arrive',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='N° ENR Arrivé'),
        ),
    ]
