# Generated by Django 5.2.8 on 2025-12-15 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0013_registrearrive_est_valide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plainte',
            name='date_plainte',
            field=models.DateField(default=datetime.date(2025, 12, 15), editable=False, verbose_name='Dates'),
        ),
    ]
