# Generated by Django 5.2.8 on 2025-12-16 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0014_alter_plainte_date_plainte'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='date_plainte',
            field=models.DateField(default=datetime.date(2025, 12, 16), editable=False, verbose_name='Dates'),
        ),
    ]
