# Generated by Django 5.2.8 on 2025-12-17 17:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0015_utilisateur_photo_alter_plainte_date_plainte'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrearrive',
            name='nbe_dossier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Dossier (TKK)'),
        ),
        migrations.AddField(
            model_name='registrearrive',
            name='plainte_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registres_entree', to='utilisateur.plainte', verbose_name='Plainte TKK liée'),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='date_plainte',
            field=models.DateField(default=datetime.date(2025, 12, 17), editable=False, verbose_name='Dates'),
        ),
    ]
