# Generated by Django 5.2.8 on 2026-01-13 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0016_registrearrive_nbe_dossier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plainte',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Antony'),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='date_plainte',
            field=models.DateField(default=datetime.date(2026, 1, 13), editable=False, verbose_name='Dates'),
        ),
    ]
