# Generated by Django 5.2.8 on 2026-01-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0017_plainte_observation_alter_plainte_date_plainte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrearrive',
            name='n_plainte_associe',
        ),
        migrations.RemoveField(
            model_name='registrearrive',
            name='provenance',
        ),
        migrations.RemoveField(
            model_name='registrearrive',
            name='texte_correspondance',
        ),
        migrations.AddField(
            model_name='registrearrive',
            name='expediteur',
            field=models.TextField(default='Non spécifié', verbose_name='Expediteur'),
        ),
        migrations.AddField(
            model_name='registrearrive',
            name='n_chrono_opj',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Chrono OPJ'),
        ),
        migrations.AddField(
            model_name='registrearrive',
            name='objet_demande',
            field=models.TextField(default='Non spécifié', verbose_name='Objet de la demande'),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='date_plainte',
            field=models.DateField(auto_now_add=True, verbose_name='Dates'),
        ),
    ]
