# Generated by Django 5.2.8 on 2026-01-25 15:12

import django.db.models.deletion
import utilisateur.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0018_remove_registrearrive_n_plainte_associe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_chrono_opj', models.CharField(editable=False, max_length=50, verbose_name='N° Chrono TKK')),
                ('date_plainte', models.DateField(auto_now_add=True, verbose_name='Dates')),
                ('ny_mpitory', models.TextField(verbose_name='Ny Mpitory (Le Plaignant)')),
                ('tranga_kolikoly', models.TextField(verbose_name='Tranga Kolikoly (Le Fait/Acte de Corruption)')),
                ('ilay_olona_kolikoly', models.TextField(verbose_name="Ilay Olona Manao kolikoly (L'auteur de la corruption)")),
                ('toerana_birao', models.TextField(blank=True, null=True, verbose_name='Toerana - Birao - Sampan-draharaha manao ilay kolikoly (Lieu - Bureau - Service de la corruption)')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Antony')),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente'), ('COURS', 'En cours de traitement'), ('TRAITEE', 'Traitée'), ('DISPATCHE', 'Dispatche'), ('CSS', 'Classer sans suite')], default='ATTENTE', max_length=10, verbose_name='Statut de la plainte')),
                ('pac_affecte', models.CharField(blank=True, choices=[('ANTANANARIVO', 'ANTANANARIVO'), ('FIANARANTSOA', 'FIANARANTSOA'), ('MAHAJANGA', 'MAHAJANGA')], max_length=50, null=True, verbose_name='PAC Affecté')),
                ('piece_jointe', models.FileField(blank=True, max_length=255, null=True, upload_to=utilisateur.models.plainte_directory_path, verbose_name='Pièce jointe (PDF, Image...)')),
                ('utilisateur_creation', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opj_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('utilisateur_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opj_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Dernière modification par')),
            ],
            options={
                'verbose_name': 'Plaintes OPJ',
                'verbose_name_plural': 'Plaintes OPJ',
                'ordering': ['-date_plainte'],
            },
        ),
    ]
