# Generated by Django 5.2.8 on 2026-01-26 19:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0019_opj'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistreST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_chrono', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('date_st', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('objet', models.TextField(verbose_name='Objet')),
                ('destinataire', models.TextField(verbose_name='Destinataire')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observation')),
                ('rappel', models.TextField(blank=True, null=True, verbose_name='Rappel')),
                ('resultat', models.TextField(blank=True, null=True, verbose_name='Résultat')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('registre_arrive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='st_detail', to='utilisateur.registrearrive', verbose_name='N° RA lié')),
                ('utilisateur_creation', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st_crees', to=settings.AUTH_USER_MODEL)),
                ('utilisateur_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registre ST',
                'ordering': ['-date_creation'],
            },
        ),
    ]
