# Generated by Django 5.2.8 on 2026-01-26 21:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0020_registrest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistreCSCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_chrono', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('date_csca', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('demandeur', models.CharField(max_length=255, verbose_name='Demandeur')),
                ('entite', models.CharField(max_length=255, verbose_name='Entité')),
                ('objet', models.TextField(verbose_name='Objet')),
                ('requisitoire_mp', models.TextField(verbose_name='Réquisitoire du MP')),
                ('intitule', models.TextField(verbose_name='Intitulé')),
                ('transmission_president', models.TextField(blank=True, null=True, verbose_name='Transmission Président')),
                ('decision', models.TextField(verbose_name='Décision')),
                ('appel', models.TextField(blank=True, null=True, verbose_name='Appel')),
                ('resultat_appel', models.TextField(blank=True, null=True, verbose_name='Résultat appel')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('registre_arrive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='csca_detail', to='utilisateur.registrearrive', verbose_name='N° RA lié')),
                ('utilisateur_creation', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registre CSCA',
                'ordering': ['-date_creation'],
            },
        ),
    ]
