# Generated by Django 5.2.8 on 2026-02-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0021_registrecsca'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='matricule',
            field=models.CharField(help_text='Format : MAT-000 (Max 10 Mo pour les pièces jointes associées)', max_length=20, null=True, verbose_name='Matricule'),
        ),
    ]
