# Generated by Django 5.2.8 on 2026-02-02 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0024_alter_messagechat_options_messagechat_date_lecture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageChat',
        ),
    ]
