# Generated by Django 5.2.8 on 2026-02-02 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0026_messagechat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistreST',
        ),
    ]
