# Generated by Django 5.2.8 on 2026-02-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0028_registrest'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
