# Generated by Django 5.2.8 on 2026-02-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0029_utilisateur_last_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='corps_d_appartenance',
            field=models.CharField(max_length=100, null=True, verbose_name='corps'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='matricule',
            field=models.CharField(max_length=20, null=True, verbose_name='Matricule'),
        ),
    ]
