# Generated by Django 5.2.8 on 2026-02-27 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0030_utilisateur_corps_d_appartenance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrecsca',
            name='registre_arrive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registres_cscas', to='utilisateur.registrearrive', verbose_name='N° RA lié'),
        ),
    ]
