# Generated by Django 5.2.8 on 2026-03-04 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0031_alter_registrecsca_registre_arrive'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistreRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rp', models.CharField(blank=True, max_length=50, verbose_name='Numéro RP')),
                ('date_entree', models.DateField(blank=True, null=True, verbose_name="Date d'entrée")),
                ('n_be_opj', models.CharField(blank=True, max_length=100, verbose_name='N° BE OPJ')),
                ('plaignant', models.CharField(blank=True, max_length=255, verbose_name='Plaignant')),
                ('infraction', models.CharField(blank=True, max_length=255, verbose_name='Infraction')),
                ('date_infraction', models.DateField(blank=True, null=True, verbose_name="Date d'infraction")),
                ('montant', models.CharField(blank=True, max_length=100, verbose_name='Montant')),
                ('date_mandat_depot', models.DateField(blank=True, null=True, verbose_name='Date mandat de dépôt')),
                ('css', models.CharField(blank=True, max_length=255, verbose_name='CSS')),
                ('observation', models.CharField(blank=True, max_length=500, verbose_name='Observation')),
                ('ref_appel', models.CharField(blank=True, max_length=255, verbose_name='Réf Appel')),
                ('ref_juge_instruction', models.CharField(blank=True, max_length=255, verbose_name="Réf Juge d'instruction")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('registre_arrive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rp_details', to='utilisateur.registrearrive', verbose_name='N° RA lié')),
                ('utilisateur_creation', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registre RP',
                'verbose_name_plural': 'Registres RP',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PersonnePhysiqueRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_personne', models.CharField(choices=[('plaignant', 'Plaignant'), ('prevenu', 'Prévenu')], default='prevenu', max_length=20, verbose_name='Type')),
                ('numero_prevenu', models.CharField(blank=True, max_length=50, verbose_name='N° Prévenu')),
                ('nom', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=150, verbose_name='Prénom')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge')),
                ('nationalite', models.CharField(blank=True, max_length=100, verbose_name='Nationalité')),
                ('genre', models.CharField(blank=True, max_length=50, verbose_name='Genre')),
                ('fonction', models.CharField(blank=True, max_length=255, verbose_name='Fonction')),
                ('registre_rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnes_physiques', to='utilisateur.registrerp', verbose_name='Dossier RP')),
            ],
            options={
                'verbose_name': 'Personne Physique RP',
                'verbose_name_plural': 'Personnes Physiques RP',
            },
        ),
        migrations.CreateModel(
            name='PersonneMoraleRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(blank=True, max_length=255, verbose_name='Raison sociale')),
                ('forme_juridique', models.CharField(blank=True, max_length=100, verbose_name='Forme juridique')),
                ('activite', models.CharField(blank=True, max_length=255, verbose_name='Activité')),
                ('registre_rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnes_morales', to='utilisateur.registrerp', verbose_name='Dossier RP')),
            ],
            options={
                'verbose_name': 'Personne Morale RP',
                'verbose_name_plural': 'Personnes Morales RP',
            },
        ),
        migrations.CreateModel(
            name='AutresMenuRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandat_arret', models.CharField(blank=True, max_length=255, verbose_name="Mandat d'arrêt")),
                ('annee', models.CharField(blank=True, max_length=10, verbose_name='Année')),
                ('citation_directe', models.CharField(blank=True, max_length=255, verbose_name='Citation directe')),
                ('renvoi_audience', models.CharField(blank=True, max_length=255, verbose_name='Renvoi audience')),
                ('requisitoire_informe', models.CharField(blank=True, max_length=255, verbose_name='Réquisitoire informé')),
                ('renvoi_cco', models.CharField(blank=True, max_length=255, verbose_name='Renvoi CCO')),
                ('registre_rp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autres_menu', to='utilisateur.registrerp', verbose_name='Dossier RP')),
            ],
            options={
                'verbose_name': 'Autres Menu RP',
            },
        ),
    ]
