# Generated by Django 5.2.8 on 2026-03-04 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0032_registrerp_personnephysiquerp_personnemoralerp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrerp',
            name='numero_rp',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Numéro RP'),
        ),
        migrations.AlterField(
            model_name='registrerp',
            name='utilisateur_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registres_rp', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
    ]
