# Generated by Django 5.2.8 on 2026-03-04 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0033_alter_registrerp_numero_rp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistreAppel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_chrono_appel', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='N° Chrono Appel')),
                ('date_appel', models.DateField(blank=True, null=True, verbose_name="Date d'appel")),
                ('n_rp', models.CharField(blank=True, max_length=100, verbose_name='N° RP')),
                ('ref_juge_instruction', models.CharField(blank=True, max_length=200, verbose_name="Réf. Juge d'instruction")),
                ('resume_affaire', models.TextField(blank=True, verbose_name="Résumé de l'affaire")),
                ('inculpation', models.TextField(blank=True, verbose_name='Inculpation')),
                ('declaration_appel', models.TextField(blank=True, verbose_name="Déclaration d'appel")),
                ('n_be_appel', models.TextField(blank=True, verbose_name='N° BE Appel')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('registre_arrive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appel_details', to='utilisateur.registrearrive', verbose_name='Registre Arrivée lié')),
                ('utilisateur_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Registre d'Appel",
                'verbose_name_plural': "Registres d'Appel",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RegistreCCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_chrono', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='N° Chrono CCO')),
                ('n_chrono_st', models.CharField(blank=True, max_length=100, verbose_name='N° Chrono ST')),
                ('date_cco', models.DateField(blank=True, null=True, verbose_name='Date CCO')),
                ('n_dossier', models.CharField(blank=True, max_length=100, verbose_name='N° Dossier')),
                ('requisitoire_parquet', models.TextField(blank=True, verbose_name='Réquisitoire du parquet')),
                ('objet', models.TextField(blank=True, verbose_name='Objet')),
                ('n_be_cco', models.TextField(blank=True, verbose_name='N° BE CCO')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('registre_arrive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cco_details', to='utilisateur.registrearrive', verbose_name='Registre Arrivée lié')),
                ('utilisateur_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cco_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registre CCO',
                'verbose_name_plural': 'Registres CCO',
                'ordering': ['-date_creation'],
            },
        ),
    ]
