"""
Django settings for sigpac project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ko9-+^kj&l@%m&p6lw=+p64um)-3n2qwp2bgrysfebs%h1o(ep'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'judy-unprotectable-quadrennially.ngrok-free.dev',
    'sigpac.com',
]

CORS_ALLOWED_ORIGINS = [
    "https://judy-unprotectable-quadrennially.ngrok-free.dev",
]

CSRF_TRUSTED_ORIGINS = [
    'https://judy-unprotectable-quadrennially.ngrok-free.dev',
    'http://127.0.0.1',
]

# Permettre l envoie de requette socket par le coonsumer sur daphne
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken', # Pour le websocket DRF Token
    'utilisateur',
    'channels', # Pour la notification en utilisant websocket
    'auditlog', # Pour l audit admin
    'pac',
]

# Gestion de token
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',   # ← Pour Android
        'rest_framework.authentication.SessionAuthentication', # ← Pour le web (inchangé)
    ],
}

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Pour lancer les fichier static si server daphne
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
]

ROOT_URLCONF = 'sigpac.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Avant wbesocket
# WSGI_APPLICATION = 'sigpac.wsgi.application'
# Avec websocket
ASGI_APPLICATION = 'sigpac.asgi.application'

# Configuration Redis (broker de messages)

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  
        'NAME': 'sigpac',                                    # Nom de votre base de données PgAdmin
        'USER': 'postgres',                      # Nom d'utilisateur PostgreSQL
        'PASSWORD': 'mandawinner2004',                 # Passwordde PostgreSQL
        'HOST': 'localhost',                                 # Adresse IP ou nom d'hôte (souvent 'localhost' ou '127.0.0.1')
        'PORT': '5432',                                      # Port par défaut de PostgreSQL (souvent 5432)
    }
}

AUTH_USER_MODEL = 'utilisateur.Utilisateur'
LOGIN_URL = 'utilisateur:login'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' # Configuration static de daphne par whitenoise
STATICFILES_DIRS = [BASE_DIR / 'static']  # ton dossier static source
STATIC_ROOT = BASE_DIR / 'staticfiles' 
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')